# Generated by Django 5.1.15 on 2026-06-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WGInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='wg0', max_length=32, unique=True, verbose_name='Interface name')),
                ('private_key', models.CharField(blank=True, max_length=64, verbose_name='Server private key')),
                ('public_key', models.CharField(blank=True, max_length=64, verbose_name='Server public key')),
                ('listen_port', models.PositiveIntegerField(default=51820, verbose_name='Listen port')),
                ('address', models.CharField(default='10.8.0.1/24', max_length=255, verbose_name='Tunnel address')),
                ('endpoint_host', models.CharField(blank=True, max_length=255, verbose_name='Public endpoint host')),
                ('dns', models.CharField(blank=True, help_text='Comma-separated DNS servers handed to clients (optional).', max_length=255, verbose_name='Client DNS')),
                ('mtu', models.PositiveIntegerField(blank=True, null=True, verbose_name='MTU')),
                ('client_allowed_ips', models.CharField(default='0.0.0.0/0, ::/0', help_text='Routes pushed into generated client configs.', max_length=255, verbose_name='Default client AllowedIPs')),
                ('persistent_keepalive', models.PositiveIntegerField(blank=True, default=25, null=True, verbose_name='Client PersistentKeepalive')),
                ('post_up', models.TextField(blank=True, verbose_name='PostUp')),
                ('post_down', models.TextField(blank=True, verbose_name='PostDown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WireGuard interface',
                'verbose_name_plural': 'WireGuard interfaces',
            },
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('public_key', models.CharField(max_length=64)),
                ('private_key', models.CharField(blank=True, max_length=64)),
                ('preshared_key', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(max_length=255, verbose_name='Tunnel address')),
                ('client_dns', models.CharField(blank=True, max_length=255)),
                ('client_allowed_ips', models.CharField(blank=True, max_length=255)),
                ('persistent_keepalive', models.PositiveIntegerField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='vpn.wginterface')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('interface', 'public_key'), name='unique_peer_pubkey_per_interface')],
            },
        ),
    ]
